sudo: required
services:
  - docker


before_install:
  - docker build -t medch1/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true medch1/docker-react npm run test

deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  region: "us-east-1"
  app:  "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-655766468898"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"